### ISSUE TITLE
Does it work with default terminal in windows 

### ISSUE THREAD

**Issue by dszvivian** [Johan-Palacios/nvim#2]
Which terminal would you suggest which will support all features in windows 

![image](https://github.com/user-attachments/assets/00a888c6-8259-44db-8a97-5314bce8ca36)

By default it shows this

**Comment by Johan-Palacios** [comment]
Try with Windows Terminal [link](https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-US&gl=US)

**Comment by Johan-Palacios** [comment]
If with windows terminal the problem continues, try deleting this [line](https://github.com/Johan-Palacios/nvim/blob/7ebb22ab468633f5c57d6c21a8056ec72be50ff3/lua/configs/options.lua#L11)

**Comment by Johan-Palacios** [comment]
Did you solve the problem?

**Comment by Johan-Palacios** [comment]
@dszvivian Did you solve the problem?
